markdown: kramdown
permalink: pretty
include: ["_pages"]
exclude:
  - "README.md"
  - "CNAME"
  - "LICENSE"
  - "package.json"
  - "node_modules"
  - "src"
  - "vendor" #jekyll travis

collections:
  pages:
    output: true
    permalink: /:path/

title : Neptune Studios LLC
url : //neptunestudios.info
theme_colour: "#333"
description : "Home of MinutePhysics, MinuteEarth, and MinuteLabs"

social :
  email : contact@neptunestudios.info

limits :
  posts : nil

# currently unused
nav:
  - title: Home
    url: /

  - title: About
    url: /about
